name: Post Video to Facebook

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: "Public URL of the video"
        required: true
      title:
        description: "Title of the video"
        required: true
      description:
        description: "Description of the video"
        required: true

jobs:
  post_video:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install expect on GitHub runner
      run: sudo apt-get update && sudo apt-get install -y expect

    - name: Use expect to SSH into VPS and run Node.js script
      run: |
        expect -c "
        spawn ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }};
        expect \"password:\";
        send \"${{ secrets.VPS_PASSWORD }}\r\";
        expect \"\$ \";  # Wait for the shell prompt
        send \"cd /home/sudeep/fbauto && node postVideo.js '${{ github.event.inputs.video_url }}' '${{ github.event.inputs.title }}' '${{ github.event.inputs.description }}'\r\";
        expect \"\$ \";  # Wait for the shell prompt after the command runs
        send \"exit\r\";
        interact"
