name: Workflow with Input

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Name of the person"
        required: true
        default: "World"
      greeting:
        description: "Greeting to use"
        required: false
        default: "Hello"

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    steps:
    - name: Print a greeting
      run: echo "${{ github.event.inputs.greeting }} ${{ github.event.inputs.name }}!"
